# Generated by Django 5.0.7 on 2024-07-31 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='user',
        ),
    ]
