# Generated by Django 5.0.7 on 2024-08-28 07:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='realised_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
