# Generated by Django 5.0.7 on 2024-08-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_choice_realised_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='realised_date',
            new_name='saved_date',
        ),
    ]
