# Generated by Django 5.0.7 on 2024-08-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_rename_realised_date_choice_saved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
